export const en = {
  loading: 'Loading data...',
  addOALink: 'Add OA link',
  tryAgain: 'Try again',
  close: 'Close',
  processing: 'Processing...',
  noData: 'No data',
  oaAddedSuccess: 'OA link added successfully!',
  oaAddedFailed: 'Failed to add OA link!',
  popupBlocked: 'Popup was blocked. Please allow popups and try again.',
  missingProjectCode: 'Missing projectCode. Please pass project-code attribute.',
  missingAccessToken: 'Missing host accessToken.',
  unableToLoad: 'Unable to load Zalo OA data.',
  failedToExchange: 'Failed to exchange module token.',
} as const
