export const vi = {
  loading: 'Đang tải dữ liệu...',
  addOALink: 'Thêm liên kết OA',
  tryAgain: 'Thử lại',
  close: 'Đóng',
  processing: 'Đang xử lý...',
  noData: 'Không có dữ liệu',
  oaAddedSuccess: 'Thêm liên kết OA thành công!',
  oaAddedFailed: 'Thêm liên kết OA thất bại!',
  popupBlocked: 'Popup bị chặn. Vui lòng cho phép popup và thử lại.',
  missingProjectCode: 'Thiếu projectCode. Vui lòng truyền thuộc tính project-code.',
  missingAccessToken: 'Thiếu host accessToken.',
  unableToLoad: 'Không thể tải dữ liệu Zalo OA.',
  failedToExchange: 'Không thể đổi module token.',
} as const
